# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ashe/Documents/projects/ai-chef

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ashe/Documents/projects/ai-chef

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ashe/Documents/projects/ai-chef/CMakeFiles /home/ashe/Documents/projects/ai-chef//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ashe/Documents/projects/ai-chef/CMakeFiles 0
.PHONY : all

# The main codegen target
codegen: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ashe/Documents/projects/ai-chef/CMakeFiles /home/ashe/Documents/projects/ai-chef//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 codegen
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ashe/Documents/projects/ai-chef/CMakeFiles 0
.PHONY : codegen

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named chef

# Build rule for target.
chef: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 chef
.PHONY : chef

# fast build rule for target.
chef/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chef.dir/build.make CMakeFiles/chef.dir/build
.PHONY : chef/fast

src/body.o: src/body.cpp.o
.PHONY : src/body.o

# target to build an object file
src/body.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chef.dir/build.make CMakeFiles/chef.dir/src/body.cpp.o
.PHONY : src/body.cpp.o

src/body.i: src/body.cpp.i
.PHONY : src/body.i

# target to preprocess a source file
src/body.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chef.dir/build.make CMakeFiles/chef.dir/src/body.cpp.i
.PHONY : src/body.cpp.i

src/body.s: src/body.cpp.s
.PHONY : src/body.s

# target to generate assembly for a file
src/body.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chef.dir/build.make CMakeFiles/chef.dir/src/body.cpp.s
.PHONY : src/body.cpp.s

src/bodypart.o: src/bodypart.cpp.o
.PHONY : src/bodypart.o

# target to build an object file
src/bodypart.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chef.dir/build.make CMakeFiles/chef.dir/src/bodypart.cpp.o
.PHONY : src/bodypart.cpp.o

src/bodypart.i: src/bodypart.cpp.i
.PHONY : src/bodypart.i

# target to preprocess a source file
src/bodypart.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chef.dir/build.make CMakeFiles/chef.dir/src/bodypart.cpp.i
.PHONY : src/bodypart.cpp.i

src/bodypart.s: src/bodypart.cpp.s
.PHONY : src/bodypart.s

# target to generate assembly for a file
src/bodypart.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chef.dir/build.make CMakeFiles/chef.dir/src/bodypart.cpp.s
.PHONY : src/bodypart.cpp.s

src/brain.o: src/brain.cpp.o
.PHONY : src/brain.o

# target to build an object file
src/brain.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chef.dir/build.make CMakeFiles/chef.dir/src/brain.cpp.o
.PHONY : src/brain.cpp.o

src/brain.i: src/brain.cpp.i
.PHONY : src/brain.i

# target to preprocess a source file
src/brain.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chef.dir/build.make CMakeFiles/chef.dir/src/brain.cpp.i
.PHONY : src/brain.cpp.i

src/brain.s: src/brain.cpp.s
.PHONY : src/brain.s

# target to generate assembly for a file
src/brain.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chef.dir/build.make CMakeFiles/chef.dir/src/brain.cpp.s
.PHONY : src/brain.cpp.s

src/ear.o: src/ear.cpp.o
.PHONY : src/ear.o

# target to build an object file
src/ear.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chef.dir/build.make CMakeFiles/chef.dir/src/ear.cpp.o
.PHONY : src/ear.cpp.o

src/ear.i: src/ear.cpp.i
.PHONY : src/ear.i

# target to preprocess a source file
src/ear.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chef.dir/build.make CMakeFiles/chef.dir/src/ear.cpp.i
.PHONY : src/ear.cpp.i

src/ear.s: src/ear.cpp.s
.PHONY : src/ear.s

# target to generate assembly for a file
src/ear.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chef.dir/build.make CMakeFiles/chef.dir/src/ear.cpp.s
.PHONY : src/ear.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chef.dir/build.make CMakeFiles/chef.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chef.dir/build.make CMakeFiles/chef.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chef.dir/build.make CMakeFiles/chef.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... codegen"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... chef"
	@echo "... src/body.o"
	@echo "... src/body.i"
	@echo "... src/body.s"
	@echo "... src/bodypart.o"
	@echo "... src/bodypart.i"
	@echo "... src/bodypart.s"
	@echo "... src/brain.o"
	@echo "... src/brain.i"
	@echo "... src/brain.s"
	@echo "... src/ear.o"
	@echo "... src/ear.i"
	@echo "... src/ear.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

